root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  prefer-const: 0
  no-empty: 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/no-unused-vars': 0
  '@typescript-eslint/no-explicit-any': 0