name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Cache
        uses: actions/cache@v2
        with: 
          path: ./node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      
      - name: Test
        run: |
          yarn install
          yarn pack_full